### ISSUE TITLE
When will you open source your code for this WSDM19 paper ?

### ISSUE THREAD

**Issue by yangliuy** [chongyangtao/MRFN#1]
Hi Chongyang,

When will you open source your code for this WSDM19 paper ?

Thanks
Best
Liu

**Comment by yangliuy** [comment]
@chongyangtao WSDM19 conference has been finished. But the source code is still not available. Thus the URL included in the paper does not provide useful information to readers.

**Comment by chongyangtao** [comment]
Hi,  Yang
	Thanks for your interest in our paper! Currently I am busy with other projects, so the code releasing has been delayed. I will let you know once we release the code.

**Comment by yangliuy** [comment]
@chongyangtao Thanks for the reply! Look forward to the code! We are from UMass CS department and we are very interested in your research on conversational response ranking.

Thanks
Best
Liu

**Comment by ghost** [comment]
> Hi, Yang
> Thanks for your interest in our paper! Currently I am busy with other projects, so the code releasing has been delayed. I will let you know once we release the code.

When will you open source your code for this WSDM19 paper ?

**Comment by linkinbird** [comment]
催更
