### ISSUE TITLE
Douban dataset code

### ISSUE THREAD

**Issue by sandan000** [chongyangtao/MRFN#2]
Hello! Can you open source your code for Douban dataset

**Comment by chongyangtao** [comment]
Hi, this code can be easily adapted to Douban dataset with word/char dictionaries and pre-trained embeddings. You can download Douban corpus according to the instruction in https://github.com/MarkWuNLP/MultiTurnResponseSelection.

**Comment by sandan000** [comment]
OK! thanks!

**Comment by bringtree** [comment]
@chongyangtao Hi, Could you share the pkl file ("word vocabulary file, pre-trained word embedding file, char vocabulary file, and pre-trained char embedding file. ") about Douban?

**Comment by WuuuZD** [comment]
Hi, Could you share the pkl file ("word vocabulary file, pre-trained word embedding file, char vocabulary file, and pre-trained char embedding file. ") about Douban?

**Comment by WuuuZD** [comment]
Hi, Could you share the pkl file ("word vocabulary file, pre-trained word embedding file, char vocabulary file, and pre-trained char embedding file. ") about Douban?

> Hi, this code can be easily adapted to Douban dataset with word/char dictionaries and pre-trained embeddings. You can download Douban corpus according to the instruction in https://github.com/MarkWuNLP/MultiTurnResponseSelection.
